### PR TITLE
Filter arrange

### PR DESCRIPTION
**Pull request by Nava2**
- Adds models
- Move filters as a column instead of atop.

screen shot 2015-04-16 at 19 00 38

### CODE REVIEW

**Comment by aforward** [comment]
Not in love with the side look.  What about a hideable / expandable one on top.  Go ahead and merge if you think it's better

**Comment by Nava2** [comment]
I don't have great feelings either way, I do prefer the side one though. Maybe @Umple could chime in? It scrolls with the page (which @aforward says is worse :stuck_out_tongue:)

**Comment by TimLethbridge** [comment]
I would have to actually use the side view. I am OK with merging. We could perhaps experiment with it for a bit.

**Comment by Nava2** [comment]
@aforward  and I talked a bit offline. We were thinking of using a single "search" bar style input, a la google search with suggested keywords.

**Comment by Nava2** [comment]
I'm going to merge this. I'll investigate "omnibar" search within #32.

**Pull request merged**
